import Foundation

import SwiftData



// MARK: - FieldOrigin



public enum FieldOrigin: String, Codable, Sendable, CaseIterable {

  case user  // Manually edited by user via UI

  case llm  // Written by an AI agent or pipeline

  case `import`  // Created by file import (PDF, markdown, etc.)

  case system  // System-generated (e.g., OCR, default values, migrations)

}



public enum CorrectionScope: String, Codable, Sendable, CaseIterable {

  case item  // Correction applies to this item only

  case project  // Correction may impact the project

  case global  // Correction applies globally (requires explicit confirmation)

}



// MARK: - FieldProvenance



/// Tracks who last modified each field, when, and by what source.

/// Stored as a JSON column (`fieldProvenanceJSON`) on each model.

public struct FieldProvenance: Codable, Sendable {

  public var fields: [String: Entry]



  public struct Entry: Codable, Sendable {

    let origin: FieldOrigin

    let modifiedAt: Date

    var scopeRaw: String?

    var scope: CorrectionScope? {

      get { scopeRaw.flatMap(CorrectionScope.init(rawValue:)) }

      set { scopeRaw = newValue?.rawValue }

    }

  }



  public func isOwned(by origin: FieldOrigin, field: String) -> Bool {

    fields[field]?.origin == origin

  }



  public func isUserOwned(field: String) -> Bool {

    isOwned(by: .user, field: field)

  }



  public func origin(for field: String) -> FieldOrigin {

    fields[field]?.origin ?? .llm

  }



  public mutating func mark(field: String, origin: FieldOrigin) {

    fields[field] = Entry(origin: origin, modifiedAt: Date())

  }



  public func encode() -> String? {

    guard let data = try? JSONEncoder().encode(self) else { return nil }

    return String(data: data, encoding: .utf8)

  }



  public static func decode(from json: String?) -> FieldProvenance {

    guard let json, let data = json.data(using: .utf8),

      let prov = try? JSONDecoder().decode(FieldProvenance.self, from: data)

    else { return FieldProvenance(fields: [:]) }

    return prov

  }



  public static let empty = FieldProvenance(fields: [:])

}



// MARK: - FieldProvidence protocol



/// Conforming models carry a FieldProvenance and know how to persist it.

public protocol FieldProvidence: AnyObject {

  var provenance: FieldProvenance { get set }

  func writeProvenance()

}



// MARK: - Project



@Model

public final class Project {

  @Attribute(.unique) public var id: UUID
  public var name: String
  public var slug: String
  public var summary: String?
  public var synthesis: String?
  public var customInstructions: String?
  public var frameworkId: String?
  public var frameworkJSON: String?
  public var statusRaw: String
  public var colorHex: String?
  public var iconName: String?
  public var createdAt: Date
  public var updatedAt: Date
  // Health & activity (Phase A)

  public var healthScore: Double?
  public var healthStatus: String?
  public var lastActivityAt: Date?
  public var synthesisUpdatedAt: Date?
  public var synthesisSourceItemID: UUID?
  // Doubts & intention

  public var intention: String?
  public var intentionIsAutoGenerated: Bool
  public var holdIngestionForDoubts: Bool
  // Field authority

  public var fieldProvenanceJSON: String?
  public var nameIsAutoGenerated: Bool
  /// When true, this project is hidden from normal project listings.

  /// Used by the config project to prevent accidental user interaction.

  public var isHidden: Bool


  public var status: ProjectStatus {

    get { ProjectStatus(rawValue: statusRaw) ?? .active }

    set { statusRaw = newValue.rawValue }

  }



  public init(

    id: UUID = UUID(),

    name: String,

    slug: String? = nil,

    summary: String? = nil,

    synthesis: String? = nil,

    customInstructions: String? = nil,

    frameworkId: String? = nil,

    frameworkJSON: String? = nil,

    status: ProjectStatus = .active,

    colorHex: String? = nil,

    iconName: String? = "folder.fill",

    createdAt: Date = Date(),

    updatedAt: Date = Date(),

    healthScore: Double? = nil,

    healthStatus: String? = nil,

    lastActivityAt: Date? = nil,

    synthesisUpdatedAt: Date? = nil,

    synthesisSourceItemID: UUID? = nil

  ) {

    self.id = id

    self.name = name

    self.slug = slug ?? name.lowercased().replacingOccurrences(of: " ", with: "-")

    self.summary = summary

    self.synthesis = synthesis

    self.customInstructions = customInstructions

    self.frameworkId = frameworkId

    self.frameworkJSON = frameworkJSON

    self.statusRaw = status.rawValue

    self.colorHex = colorHex

    self.iconName = iconName

    self.createdAt = createdAt

    self.updatedAt = updatedAt

    self.healthScore = healthScore

    self.healthStatus = healthStatus

    self.lastActivityAt = lastActivityAt

    self.synthesisUpdatedAt = synthesisUpdatedAt

    self.synthesisSourceItemID = synthesisSourceItemID

    self.intention = nil

    self.intentionIsAutoGenerated = false

    self.holdIngestionForDoubts = true

    self.fieldProvenanceJSON = nil

    self.nameIsAutoGenerated = true

    self.isHidden = false

  }

}



// MARK: - Project + FieldProvidence



extension Project: FieldProvidence {

  public var provenance: FieldProvenance {

    get { FieldProvenance.decode(from: fieldProvenanceJSON) }

    set { fieldProvenanceJSON = newValue.encode() }

  }



  public func writeProvenance() {

    fieldProvenanceJSON = provenance.encode()

  }

}



public enum ProjectStatus: String, Codable, CaseIterable {

  case active

  case archived

  case completed

}



// MARK: - TaskItem



@Model

public final class TaskItem {

  @Attribute(.unique) public var id: UUID
  public var projectID: UUID?
  public var title: String
  public var statusRaw: String
  public var priorityRaw: String
  public var ownerName: String?
  public var dueAt: Date?
  public var sourceItemID: UUID?
  public var sourceSegmentIDs: String?
  public var confidence: Double?
  public var notes: String?
  public var createdAt: Date
  public var updatedAt: Date
  // Field authority

  public var createdByRaw: String?
  public var fieldProvenanceJSON: String?


  public var status: TaskStatus {

    get { TaskStatus(rawValue: statusRaw) ?? .todo }

    set { statusRaw = newValue.rawValue }

  }



  var priority: TaskPriority {

    get { TaskPriority(rawValue: priorityRaw) ?? .medium }

    set { priorityRaw = newValue.rawValue }

  }



  var sourceSegmentIDList: [String] {

    guard let json = sourceSegmentIDs, let data = json.data(using: .utf8),

      let list = try? JSONDecoder().decode([String].self, from: data)

    else { return [] }

    return list

  }



  var createdBy: FieldOrigin? {

    get { createdByRaw.flatMap(FieldOrigin.init(rawValue:)) }

    set { createdByRaw = newValue?.rawValue }

  }



  var fieldProvenance: FieldProvenance {

    get { FieldProvenance.decode(from: fieldProvenanceJSON) }

    set { fieldProvenanceJSON = newValue.encode() }

  }



  public init(

    id: UUID = UUID(),

    projectID: UUID? = nil,

    title: String,

    status: TaskStatus = .todo,

    priority: TaskPriority = .medium,

    ownerName: String? = nil,

    dueAt: Date? = nil,

    sourceItemID: UUID? = nil,

    sourceSegmentIDs: [String] = [],

    confidence: Double? = nil,

    notes: String? = nil,

    createdAt: Date = Date(),

    updatedAt: Date = Date()

  ) {

    self.id = id

    self.projectID = projectID

    self.title = title

    self.statusRaw = status.rawValue

    self.priorityRaw = priority.rawValue

    self.ownerName = ownerName

    self.dueAt = dueAt

    self.sourceItemID = sourceItemID

    self.sourceSegmentIDs =

      sourceSegmentIDs.isEmpty

      ? nil

      : (try? JSONEncoder().encode(sourceSegmentIDs)).flatMap { String(data: $0, encoding: .utf8) }

    self.confidence = confidence

    self.notes = notes

    self.createdAt = createdAt

    self.updatedAt = updatedAt

    self.createdByRaw = nil

    self.fieldProvenanceJSON = nil

  }

}



// MARK: - TaskItem + FieldProvidence



extension TaskItem: FieldProvidence {

  public var provenance: FieldProvenance {

    get { FieldProvenance.decode(from: fieldProvenanceJSON) }

    set { fieldProvenanceJSON = newValue.encode() }

  }



  public func writeProvenance() {

    fieldProvenanceJSON = provenance.encode()

  }

}



public enum TaskStatus: String, Codable, CaseIterable {

  case todo

  case inProgress

  case done

  case cancelled

}



public enum TaskPriority: String, Codable, CaseIterable {

  case low

  case medium

  case high

  case critical

}



// MARK: - Person



@Model

public final class Person {

  @Attribute(.unique) public var id: UUID
  public var displayName: String
  @Attribute(.unique) public var canonicalKey: String
  public var email: String?
  public var role: String?
  public var createdAt: Date


  public init(

    id: UUID = UUID(),

    displayName: String,

    canonicalKey: String? = nil,

    email: String? = nil,

    role: String? = nil,

    createdAt: Date = Date()

  ) {

    self.id = id

    self.displayName = displayName

    self.canonicalKey =

      canonicalKey ?? displayName.lowercased().trimmingCharacters(in: .whitespaces)

    self.email = email

    self.role = role

    self.createdAt = createdAt

  }

}



// MARK: - GraphEdge



@Model

public final class GraphEdge {

  @Attribute(.unique) public var id: UUID
  public var fromID: UUID
  public var toID: UUID
  public var edgeTypeRaw: String
  public var weight: Double
  public var provenanceItemID: UUID?
  public var provenanceSegmentIDs: String?
  public var createdAt: Date


  var edgeType: EdgeType {

    get { EdgeType(rawValue: edgeTypeRaw) ?? .relatesTo }

    set { edgeTypeRaw = newValue.rawValue }

  }



  var provenanceSegmentIDList: [String] {

    guard let json = provenanceSegmentIDs, let data = json.data(using: .utf8),

      let list = try? JSONDecoder().decode([String].self, from: data)

    else { return [] }

    return list

  }



  public init(

    id: UUID = UUID(),

    fromID: UUID,

    toID: UUID,

    edgeType: EdgeType,

    weight: Double = 1.0,

    provenanceItemID: UUID? = nil,

    provenanceSegmentIDs: [String] = [],

    createdAt: Date = Date()

  ) {

    self.id = id

    self.fromID = fromID

    self.toID = toID

    self.edgeTypeRaw = edgeType.rawValue

    self.weight = weight

    self.provenanceItemID = provenanceItemID

    self.provenanceSegmentIDs =

      provenanceSegmentIDs.isEmpty

      ? nil

      : (try? JSONEncoder().encode(provenanceSegmentIDs)).flatMap {

        String(data: $0, encoding: .utf8)

      }

    self.createdAt = createdAt

  }

}



public enum EdgeType: String, Codable, CaseIterable {

  case relatesTo

  case mentions

  case supports

  case assignedTo

  case blockedBy

  case belongsTo

  case produced

  case precedes

  case references

  case contradicts

}



// MARK: - Entity



@Model

public final class Entity {

  @Attribute(.unique) public var id: UUID
  public var kindRaw: String
  public var displayName: String
  @Attribute(.unique) public var canonicalKey: String


  var kind: EntityKind {

    get { EntityKind(rawValue: kindRaw) ?? .other }

    set { kindRaw = newValue.rawValue }

  }



  public init(

    id: UUID = UUID(),

    kind: EntityKind,

    displayName: String,

    canonicalKey: String? = nil

  ) {

    self.id = id

    self.kindRaw = kind.rawValue

    self.displayName = displayName

    self.canonicalKey =

      canonicalKey

      ?? "\(kind.rawValue):\(displayName.lowercased().trimmingCharacters(in: .whitespaces))"

  }

}



public enum EntityKind: String, Codable, CaseIterable {

  case person

  case organization

  case system

  case repository

  case ticket

  case location

  case other

}



// MARK: - Project Framework (stored as JSON in Project.frameworkJSON)



public struct ProjectFramework: Codable, Sendable {

  public let id: String

  public let name: String

  public let description: String

  public let itemAnalysis: AnalysisConfig

  public let projectSynthesis: SynthesisConfig

  public let views: [ViewDefinition]

  public let entityKinds: [String]

  public let edgeTypes: [String]

  public init(

    id: String, name: String, description: String, itemAnalysis: AnalysisConfig,

    projectSynthesis: SynthesisConfig, views: [ViewDefinition], entityKinds: [String],

    edgeTypes: [String]

  ) {

    self.id = id

    self.name = name

    self.description = description

    self.itemAnalysis = itemAnalysis

    self.projectSynthesis = projectSynthesis

    self.views = views

    self.entityKinds = entityKinds

    self.edgeTypes = edgeTypes

  }

}



public struct AnalysisConfig: Codable, Sendable {

  public let systemPrompt: String

  public let outputSchema: AnalysisOutputSchema

  public let renderAs: [FieldRenderer]

  public init(systemPrompt: String, outputSchema: AnalysisOutputSchema, renderAs: [FieldRenderer]) {

    self.systemPrompt = systemPrompt

    self.outputSchema = outputSchema

    self.renderAs = renderAs

  }

}



public struct AnalysisOutputSchema: Codable, Sendable {

  public let type: String  // "object"

  public let properties: [String: SchemaProperty]

  public let required: [String]?

  public init(

    type: String = "object", properties: [String: SchemaProperty] = [:], required: [String]? = nil

  ) {

    self.type = type

    self.properties = properties

    self.required = required

  }

}



public struct SchemaProperty: Codable, Sendable {

  public let type: String

  public let items: SchemaItems?

  public let properties: [String: SchemaProperty]?

  public let description: String?

  public init(

    type: String, items: SchemaItems? = nil, properties: [String: SchemaProperty]? = nil,

    description: String? = nil

  ) {

    self.type = type

    self.items = items

    self.properties = properties

    self.description = description

  }

}



public struct SchemaItems: Codable, Sendable {

  public let type: String

  public let properties: [String: SchemaProperty]?



  public init(type: String, properties: [String: SchemaProperty]? = nil) {

    self.type = type

    self.properties = properties

  }

}



public struct SynthesisConfig: Codable, Sendable {

  public let systemPrompt: String

  public let outputSchema: AnalysisOutputSchema

  public init(systemPrompt: String, outputSchema: AnalysisOutputSchema) {

    self.systemPrompt = systemPrompt

    self.outputSchema = outputSchema

  }

}



public struct FieldRenderer: Codable, Sendable {

  public let field: String

  public let type: RenderType

  public let title: String

  public let icon: String?

  public init(field: String, type: RenderType, title: String, icon: String? = nil) {

    self.field = field

    self.type = type

    self.title = title

    self.icon = icon

  }

}



public enum RenderType: String, Codable, Sendable {

  case card

  case list

  case table

  case markdown

  case chips

  case timeline

}



public struct ViewDefinition: Codable, Sendable {

  public let id: String

  public let title: String

  public let type: ViewType

  public let source: String

  public init(id: String, title: String, type: ViewType, source: String) {

    self.id = id

    self.title = title

    self.type = type

    self.source = source

  }



  /// Validates that the view definition has a supported type and non-empty source.

  public var isValid: Bool {

    let validSources: Set<String> = [

      "items", "tasks", "edges", "analysis.hypotheses", "analysis.findings", "analysis.ideas",

      "analysis.competencies", "analysis.cases", "analysis.stories", "tags", "entities",

    ]

    return !source.isEmpty && validSources.contains(source)

  }

}



public enum ViewType: String, Codable, Sendable {

  case list

  case kanban

  case timeline

  case graph

  case cards

  case table

  case markdown

  case chips

}



// MARK: - Lens (unified Framework + ai_config.json lenses)



public enum LensCategory: String, Codable, Sendable, CaseIterable {

  case domain  // meeting, research, legal, product, coaching

  case analytical  // risk_analysis, executive_summary, design_critique

  case personal  // journal, brainstorm

  case custom

}



public struct Lens: Codable, Sendable, Identifiable {

  public var id: String
  public var name: String
  public var description: String
  public var icon: String
  public var category: LensCategory
  public var framework: ProjectFramework?
  public var systemPromptOverride: String?
  public var userPromptTemplate: String?


  var hasFramework: Bool { framework != nil }

}



// MARK: - Preset



/// Exportable project behavior preset. Contains process, not data.

public struct Preset: Codable, Sendable, Identifiable {

  public var id: String
  public var name: String
  public var description: String
  public var lensID: String?
  public var frameworkJSON: String?
  public var customInstructions: String?
  public var markdownTemplates: [String: String]
  public var analysisRules: [String]
  public var doubtRules: [String]
  public var relevanceCriteria: [String]
  public var llmBehavior: String?
  public var exportedAt: Date
  public var version: Int


  public init(

    id: String, name: String, description: String = "", lensID: String? = nil,

    frameworkJSON: String? = nil, customInstructions: String? = nil,

    markdownTemplates: [String: String] = [:], analysisRules: [String] = [],

    doubtRules: [String] = [], relevanceCriteria: [String] = [],

    llmBehavior: String? = nil, exportedAt: Date = Date(), version: Int = 1

  ) {

    self.id = id

    self.name = name

    self.description = description

    self.lensID = lensID

    self.frameworkJSON = frameworkJSON

    self.customInstructions = customInstructions

    self.markdownTemplates = markdownTemplates

    self.analysisRules = analysisRules

    self.doubtRules = doubtRules

    self.relevanceCriteria = relevanceCriteria

    self.llmBehavior = llmBehavior

    self.exportedAt = exportedAt

    self.version = version

  }

}



// MARK: - ProjectFrame (Scope)



@Model

public final class ProjectFrame {

  @Attribute(.unique) public var id: UUID
  public var projectID: UUID
  public var parentFrameID: UUID?
  public var name: String
  public var lensID: String?
  // [String] is NOT supported as a direct SwiftData attribute — CoreData

  // cannot materialize "Array<String>". Store as JSON string instead.

  private var _filterTagsJSON: String = "[]"

  public var filterDateStart: Date?
  public var filterDateEnd: Date?
  private var _filterItemTypesJSON: String = "[]"

  public var createdAt: Date


  var isRoot: Bool { parentFrameID == nil }



  @Transient

  var filterTags: [String] {

    get { Self.decodeJSONArray(_filterTagsJSON) }

    set { _filterTagsJSON = Self.encodeJSONArray(newValue) }

  }



  @Transient

  var filterItemTypes: [String] {

    get { Self.decodeJSONArray(_filterItemTypesJSON) }

    set { _filterItemTypesJSON = Self.encodeJSONArray(newValue) }

  }



  private static func decodeJSONArray(_ json: String) -> [String] {

    guard let data = json.data(using: .utf8),

      let result = try? JSONDecoder().decode([String].self, from: data)

    else {

      return []

    }

    return result

  }



  private static func encodeJSONArray(_ array: [String]) -> String {

    guard !array.isEmpty else { return "[]" }

    if let data = try? JSONEncoder().encode(array),

      let json = String(data: data, encoding: .utf8)

    {

      return json

    }

    return "[]"

  }



  /// Returns true if an item matches this frame's scope.

  func includes(itemType: String, createdAt itemDate: Date, tags itemTags: [String]) -> Bool {

    let itemTypes = filterItemTypes

    if !itemTypes.isEmpty, !itemTypes.contains(itemType) { return false }

    if let start = filterDateStart, itemDate < start { return false }

    if let end = filterDateEnd, itemDate > end { return false }

    let tags = filterTags

    if !tags.isEmpty {

      let hasTag = tags.contains(where: { t in

        itemTags.contains { $0.localizedCaseInsensitiveCompare(t) == .orderedSame }

      })

      if !hasTag { return false }

    }

    return true

  }



  public init(

    id: UUID = UUID(), projectID: UUID, parentFrameID: UUID? = nil, name: String,

    lensID: String? = nil, filterTags: [String] = [], filterDateStart: Date? = nil,

    filterDateEnd: Date? = nil, filterItemTypes: [String] = []

  ) {

    self.id = id

    self.projectID = projectID

    self.parentFrameID = parentFrameID

    self.name = name

    self.lensID = lensID

    self._filterTagsJSON = Self.encodeJSONArray(filterTags)

    self.filterDateStart = filterDateStart

    self.filterDateEnd = filterDateEnd

    self._filterItemTypesJSON = Self.encodeJSONArray(filterItemTypes)

    self.createdAt = Date()

  }

}



// MARK: - Versioning



public enum SnapshotTrigger: String, Codable, CaseIterable, Sendable {

  case manual

  case auto_ingestion

  case auto_milestone

}



/// Individual field change record. The atom of version history.

@Model

public final class ChangeRecord {

  @Attribute(.unique) public var id: UUID
  public var entityType: String
  public var entityID: UUID
  public var projectID: UUID?
  public var field: String
  public var previousValue: String?
  public var newValue: String?
  public var originRaw: String
  public var timestamp: Date
  public var snapshotID: UUID?


  var origin: FieldOrigin {

    get { FieldOrigin(rawValue: originRaw) ?? .llm }

    set { originRaw = newValue.rawValue }

  }



  public init(

    id: UUID = UUID(), entityType: String, entityID: UUID, projectID: UUID? = nil,

    field: String, previousValue: String? = nil, newValue: String? = nil,

    origin: FieldOrigin = .llm, timestamp: Date = Date(), snapshotID: UUID? = nil

  ) {

    self.id = id

    self.entityType = entityType

    self.entityID = entityID

    self.projectID = projectID

    self.field = field

    self.previousValue = previousValue

    self.newValue = newValue

    self.originRaw = origin.rawValue

    self.timestamp = timestamp

    self.snapshotID = snapshotID

  }

}



/// A point-in-time snapshot of a project's state.

@Model

public final class ProjectSnapshot {

  @Attribute(.unique) public var id: UUID
  public var projectID: UUID
  public var label: String?
  public var triggerRaw: String
  public var createdAt: Date
  public var changeCount: Int
  public var summary: String?


  var trigger: SnapshotTrigger {

    get { SnapshotTrigger(rawValue: triggerRaw) ?? .manual }

    set { triggerRaw = newValue.rawValue }

  }



  public init(

    id: UUID = UUID(), projectID: UUID, label: String? = nil,

    trigger: SnapshotTrigger = .manual, createdAt: Date = Date(),

    changeCount: Int = 0, summary: String? = nil

  ) {

    self.id = id

    self.projectID = projectID

    self.label = label

    self.triggerRaw = trigger.rawValue

    self.createdAt = createdAt

    self.changeCount = changeCount

    self.summary = summary

  }

}



// MARK: - Agent Suggestion (Signal System)



/// The "atom of attention" — a signal raised by the system or LLM.

/// Types: risk, alert, opportunity, change, contradiction, pattern, doubt, new_project, emerging_problem,

///        task, edge, annotation, decision, field_change.

/// Status lifecycle: visible → seen → (acknowledged|approved|rejected|archived|auto_archived|transformed|ignored)

@Model

public final class AgentSuggestion {

  @Attribute(.unique) public var id: UUID
  public var projectID: UUID?
  public var type: String
  public var title: String
  public var body: String?
  public var status: String
  public var confidence: Double?
  public var sourceItemID: UUID?
  public var sourceSegmentIDs: String?  // JSON array
  public var payloadJSON: String?  // JSON for the actual action
  public var createdAt: Date
  public var resolvedAt: Date?


  // Contextual priority scores (0-1)

  public var impactScore: Double?
  public var urgencyScore: Double?
  public var relevanceScore: Double?


  // Resolution tracking

  public var resolutionReason: String?
  public var resolvedByRaw: String?
  public var isCritical: Bool


  public init(

    id: UUID = UUID(), projectID: UUID? = nil, type: String, title: String,

    body: String? = nil, status: String = "visible", confidence: Double? = nil,

    sourceItemID: UUID? = nil, sourceSegmentIDs: [String]? = nil,

    payloadJSON: String? = nil, createdAt: Date = Date(), resolvedAt: Date? = nil,

    impactScore: Double? = nil, urgencyScore: Double? = nil, relevanceScore: Double? = nil,

    resolutionReason: String? = nil, resolvedByRaw: String? = nil, isCritical: Bool = false

  ) {

    self.id = id

    self.projectID = projectID

    self.type = type

    self.title = title

    self.body = body

    self.status = status

    self.confidence = confidence

    self.sourceItemID = sourceItemID

    self.sourceSegmentIDs = sourceSegmentIDs.flatMap { try? JSONEncoder().encode($0) }.flatMap {

      String(data: $0, encoding: .utf8)

    }

    self.payloadJSON = payloadJSON

    self.createdAt = createdAt

    self.resolvedAt = resolvedAt

    self.impactScore = impactScore

    self.urgencyScore = urgencyScore

    self.relevanceScore = relevanceScore

    self.resolutionReason = resolutionReason

    self.resolvedByRaw = resolvedByRaw

    self.isCritical = isCritical

  }



  /// Computed contextual priority (0-100). Uses stored scores or falls back to confidence.

  var computedPriority: Double {

    let impact = impactScore ?? 0.5

    let urgency = urgencyScore ?? 0.5

    let relevance = relevanceScore ?? 0.5

    let base = (impact * 0.4 + urgency * 0.35 + relevance * 0.25) * 100

    // Age decay: signals older than 7 days lose up to 30% priority

    let ageDays = Date().timeIntervalSince(createdAt) / 86400

    let decay = min(ageDays / 7.0 * 0.3, 0.3)

    return max(base * (1.0 - decay), 5.0)

  }



  /// Whether this signal is in an active (unresolved) state.

  public var isActive: Bool {

    ["visible", "seen", "acknowledged"].contains(status)

  }

}



// MARK: - Queue Entry (Processing Queue)



/// Persisted job in the processing queue. Survives app kills via SwiftData.

@Model

public final class QueueEntry {

  @Attribute(.unique) public var id: UUID
  public var itemID: UUID
  public var projectID: UUID?
  public var statusRaw: String
  public var priority: Int
  public var queuedAt: Date
  public var startedAt: Date?
  public var completedAt: Date?
  public var retryCount: Int
  public var maxRetries: Int
  public var lastError: String?
  public var position: Int


  var status: QueueStatus {

    get { QueueStatus(rawValue: statusRaw) ?? .queued }

    set { statusRaw = newValue.rawValue }

  }



  public init(

    id: UUID = UUID(),

    itemID: UUID,

    projectID: UUID? = nil,

    status: QueueStatus = .queued,

    priority: Int = 50,

    queuedAt: Date = Date(),

    startedAt: Date? = nil,

    completedAt: Date? = nil,

    retryCount: Int = 0,

    maxRetries: Int = 2,

    lastError: String? = nil,

    position: Int = 0

  ) {

    self.id = id

    self.itemID = itemID

    self.projectID = projectID

    self.statusRaw = status.rawValue

    self.priority = priority

    self.queuedAt = queuedAt

    self.startedAt = startedAt

    self.completedAt = completedAt

    self.retryCount = retryCount

    self.maxRetries = maxRetries

    self.lastError = lastError

    self.position = position

  }

}



public enum QueueStatus: String, Codable, CaseIterable, Sendable {

  case queued

  case processing

  case paused

  case done

  case failed

  case cancelled

  case waitingForUser = "waiting_for_user"

}



// MARK: - ProjectDerivedItem



public enum ProjectDerivedType: String, Codable, Sendable, CaseIterable {

  case synthesis  // Living synthesis document — one per project

  case task  // Actionable item with status, priority, dueAt, owner

  case signal  // Alert, risk, doubt, opportunity

  case connection  // Proposed edge between items

}



public enum ProjectDerivedStatus: String, Codable, Sendable, CaseIterable {

  // Task statuses

  case todo

  case inProgress

  case done

  case cancelled

  // Signal statuses

  case visible

  case acknowledged

  case resolved

  case dismissed

}



/// Persisted derivation created by the Project Agent.

/// Does NOT replace item-level derivations (those stay in item analysis JSON).

/// Appears in the project file browser alongside KnowledgeItems.

@Model

public final class ProjectDerivedItem {

  @Attribute(.unique) public var id: UUID
  public var projectID: UUID
  public var sourceItemID: UUID?  // nil = synthesis (project-level, not tied to one item)
  public var typeRaw: String
  public var title: String
  public var bodyJSON: String?  // Structured content specific to type (taskJSON, signalJSON, synthesisJSON)
  public var statusRaw: String?
  public var priorityRaw: String?  // For tasks: low, medium, high, critical
  public var ownerName: String?  // For tasks: assigned person
  public var dueAt: Date?  // For tasks: deadline
  public var confidence: Double?  // For signals: 0-1
  public var isCritical: Bool  // For signals: demands immediate attention
  public var createdAt: Date
  public var updatedAt: Date
  public var resolvedAt: Date?  // For signals: when resolved
  public var resolutionReason: String?  // For signals: why resolved
  public var reprocessContext: String?  // If created via reprocess, the context used


  var type: ProjectDerivedType {

    get { ProjectDerivedType(rawValue: typeRaw) ?? .synthesis }

    set { typeRaw = newValue.rawValue }

  }



  var status: ProjectDerivedStatus? {

    get { statusRaw.flatMap(ProjectDerivedStatus.init(rawValue:)) }

    set { statusRaw = newValue?.rawValue }

  }



  public init(

    id: UUID = UUID(),

    projectID: UUID,

    sourceItemID: UUID? = nil,

    type: ProjectDerivedType,

    title: String,

    bodyJSON: String? = nil,

    status: ProjectDerivedStatus? = nil,

    priority: TaskPriority? = nil,

    ownerName: String? = nil,

    dueAt: Date? = nil,

    confidence: Double? = nil,

    isCritical: Bool = false,

    createdAt: Date = Date(),

    updatedAt: Date = Date(),

    resolvedAt: Date? = nil,

    resolutionReason: String? = nil,

    reprocessContext: String? = nil

  ) {

    self.id = id

    self.projectID = projectID

    self.sourceItemID = sourceItemID

    self.typeRaw = type.rawValue

    self.title = title

    self.bodyJSON = bodyJSON

    self.statusRaw = status?.rawValue

    self.priorityRaw = priority?.rawValue

    self.ownerName = ownerName

    self.dueAt = dueAt

    self.confidence = confidence

    self.isCritical = isCritical

    self.createdAt = createdAt

    self.updatedAt = updatedAt

    self.resolvedAt = resolvedAt

    self.resolutionReason = resolutionReason

    self.reprocessContext = reprocessContext

  }

}



// MARK: - Convenience helpers



extension ProjectDerivedItem {

  /// Whether this derived item is actionable (task or active signal).

  var isActionable: Bool {

    switch type {

    case .task: status == .todo || status == .inProgress

    case .signal: status == .visible || status == .acknowledged

    default: false

    }

  }



  /// Whether this item is in a terminal (non-active) state.

  var isResolved: Bool {

    switch type {

    case .task: status == .done || status == .cancelled

    case .signal: status == .resolved || status == .dismissed

    case .synthesis, .connection: false

    }

  }



  /// Icon name for file browser display.

  var displayIcon: String {

    switch type {

    case .synthesis: "doc.richtext"

    case .task: "checklist"

    case .signal: signalIcon

    case .connection: "arrow.triangle.branch"

    }

  }



  private var signalIcon: String {

    guard let body = bodyJSON, let data = body.data(using: .utf8),

      let json = try? JSONDecoder().decode(SignalBody.self, from: data)

    else { return "dot.radiowaves.left.and.right" }

    switch json.signalType {

    case "risk": return "exclamationmark.triangle.fill"

    case "alert": return "bell.fill"

    case "opportunity": return "lightbulb.fill"

    case "doubt": return "questionmark.circle.fill"

    case "pattern": return "rectangle.3.group.fill"

    case "contradiction": return "arrow.triangle.swap"

    default: return "waveform.path.ecg"

    }

  }

}



/// Structured body for signal-type derived items.

public struct SignalBody: Codable, Sendable {

  public var signalType: String  // risk, alert, opportunity, doubt, pattern, contradiction
  public var description: String
  public var suggestedAction: String?  // What the agent suggests doing about it
  public var relatedItemIDs: [UUID]?  // Items this signal connects
  public var impactScore: Double?  // 0-1
  public var urgencyScore: Double?  // 0-1
}



/// Structured body for task-type derived items.

struct TaskBody: Codable, Sendable {

  public var description: String?
  public var sourceSegmentIDs: [String]?
  public var aiGenerated: Bool
  public var suggestedByItemID: UUID?
}



/// Structured body for synthesis-type derived items.

struct SynthesisBody: Codable, Sendable {

  public var markdown: String  // Full synthesis in markdown
  public var sections: [SynthesisSection]  // Parsed sections for rendering
  public var metrics: [SynthesisMetric]  // Computed metrics
  public var updatedFromItemIDs: [UUID]  // Items that contributed to latest version
  public var generatedAt: Date
}



public struct SynthesisSection: Codable, Sendable {

  public var id: String
  public var title: String
  public var renderType: String  // "markdown", "cards", "table", "metrics", "timeline"
  public var content: String  // Markdown or JSON depending on renderType
  public var order: Int

  public init(title: String = "", body: String? = nil) {
    self.title = title; self.body = body
  }
}



public struct SynthesisMetric: Codable, Sendable {

  public var id: String
  public var label: String
  public var value: Double
  public var format: String  // "number", "percentage", "days", "score"
  public var status: String  // "healthy", "warning", "critical", "neutral"
  public var icon: String?

  public init(label: String = "", value: Double = 0, format: String = "", status: String = "", icon: String? = nil) {
    self.label = label; self.value = value; self.format = format; self.status = status; self.icon = icon
  }
}
