import Foundation
import SwiftData

// MARK: - FieldOrigin

enum FieldOrigin: String, Codable, Sendable, CaseIterable {
    case user       // Manually edited by user via UI
    case llm        // Written by an AI agent or pipeline
    case `import`   // Created by file import (PDF, markdown, etc.)
    case system     // System-generated (e.g., OCR, default values, migrations)
}

enum CorrectionScope: String, Codable, Sendable, CaseIterable {
    case item       // Correction applies to this item only
    case project    // Correction may impact the project
    case global     // Correction applies globally (requires explicit confirmation)
}

// MARK: - FieldProvenance

/// Tracks who last modified each field, when, and by what source.
/// Stored as a JSON column (`fieldProvenanceJSON`) on each model.
struct FieldProvenance: Codable, Sendable {
    var fields: [String: Entry]

    struct Entry: Codable, Sendable {
        let origin: FieldOrigin
        let modifiedAt: Date
        var scopeRaw: String?
        var scope: CorrectionScope? {
            get { scopeRaw.flatMap(CorrectionScope.init(rawValue:)) }
            set { scopeRaw = newValue?.rawValue }
        }
    }

    func isOwned(by origin: FieldOrigin, field: String) -> Bool {
        fields[field]?.origin == origin
    }

    func isUserOwned(field: String) -> Bool {
        isOwned(by: .user, field: field)
    }

    func origin(for field: String) -> FieldOrigin {
        fields[field]?.origin ?? .llm
    }

    mutating func mark(field: String, origin: FieldOrigin) {
        fields[field] = Entry(origin: origin, modifiedAt: Date())
    }

    func encode() -> String? {
        guard let data = try? JSONEncoder().encode(self) else { return nil }
        return String(data: data, encoding: .utf8)
    }

    static func decode(from json: String?) -> FieldProvenance {
        guard let json, let data = json.data(using: .utf8),
              let prov = try? JSONDecoder().decode(FieldProvenance.self, from: data)
        else { return FieldProvenance(fields: [:]) }
        return prov
    }

    static let empty = FieldProvenance(fields: [:])
}

// MARK: - FieldProvidence protocol

/// Conforming models carry a FieldProvenance and know how to persist it.
protocol FieldProvidence: AnyObject {
    var provenance: FieldProvenance { get set }
    func writeProvenance()
}

// MARK: - Project

@Model
final class Project {
    @Attribute(.unique) var id: UUID
    var name: String
    var slug: String
    var summary: String?
    var synthesis: String?
    var customInstructions: String?
    var frameworkId: String?
    var frameworkJSON: String?
    var statusRaw: String
    var colorHex: String?
    var iconName: String?
    var createdAt: Date
    var updatedAt: Date
    // Health & activity (Phase A)
    var healthScore: Double?
    var healthStatus: String?
    var lastActivityAt: Date?
    var synthesisUpdatedAt: Date?
    var synthesisSourceItemID: UUID?
    // Doubts & intention
    var intention: String?
    var intentionIsAutoGenerated: Bool
    var holdIngestionForDoubts: Bool
    // Field authority
    var fieldProvenanceJSON: String?
    var nameIsAutoGenerated: Bool
    /// When true, this project is hidden from normal project listings.
    /// Used by the config project to prevent accidental user interaction.
    var isHidden: Bool

    var status: ProjectStatus {
        get { ProjectStatus(rawValue: statusRaw) ?? .active }
        set { statusRaw = newValue.rawValue }
    }

    init(
        id: UUID = UUID(),
        name: String,
        slug: String? = nil,
        summary: String? = nil,
        synthesis: String? = nil,
        customInstructions: String? = nil,
        frameworkId: String? = nil,
        frameworkJSON: String? = nil,
        status: ProjectStatus = .active,
        colorHex: String? = nil,
        iconName: String? = "folder.fill",
        createdAt: Date = Date(),
        updatedAt: Date = Date(),
        healthScore: Double? = nil,
        healthStatus: String? = nil,
        lastActivityAt: Date? = nil,
        synthesisUpdatedAt: Date? = nil,
        synthesisSourceItemID: UUID? = nil
    ) {
        self.id = id
        self.name = name
        self.slug = slug ?? name.lowercased().replacingOccurrences(of: " ", with: "-")
        self.summary = summary
        self.synthesis = synthesis
        self.customInstructions = customInstructions
        self.frameworkId = frameworkId
        self.frameworkJSON = frameworkJSON
        self.statusRaw = status.rawValue
        self.colorHex = colorHex
        self.iconName = iconName
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.healthScore = healthScore
        self.healthStatus = healthStatus
        self.lastActivityAt = lastActivityAt
        self.synthesisUpdatedAt = synthesisUpdatedAt
        self.synthesisSourceItemID = synthesisSourceItemID
        self.intention = nil
        self.intentionIsAutoGenerated = false
        self.holdIngestionForDoubts = true
        self.fieldProvenanceJSON = nil
        self.nameIsAutoGenerated = true
        self.isHidden = false
    }
}

// MARK: - Project + FieldProvidence

extension Project: FieldProvidence {
    var provenance: FieldProvenance {
        get { FieldProvenance.decode(from: fieldProvenanceJSON) }
        set { fieldProvenanceJSON = newValue.encode() }
    }

    func writeProvenance() {
        fieldProvenanceJSON = provenance.encode()
    }
}

enum ProjectStatus: String, Codable, CaseIterable {
    case active
    case archived
    case completed
}

// MARK: - TaskItem

@Model
final class TaskItem {
    @Attribute(.unique) var id: UUID
    var projectID: UUID?
    var title: String
    var statusRaw: String
    var priorityRaw: String
    var ownerName: String?
    var dueAt: Date?
    var sourceItemID: UUID?
    var sourceSegmentIDs: String?
    var confidence: Double?
    var notes: String?
    var createdAt: Date
    var updatedAt: Date
    // Field authority
    var createdByRaw: String?
    var fieldProvenanceJSON: String?

    var status: TaskStatus {
        get { TaskStatus(rawValue: statusRaw) ?? .todo }
        set { statusRaw = newValue.rawValue }
    }

    var priority: TaskPriority {
        get { TaskPriority(rawValue: priorityRaw) ?? .medium }
        set { priorityRaw = newValue.rawValue }
    }

    var sourceSegmentIDList: [String] {
        guard let json = sourceSegmentIDs, let data = json.data(using: .utf8),
              let list = try? JSONDecoder().decode([String].self, from: data) else { return [] }
        return list
    }

    var createdBy: FieldOrigin? {
        get { createdByRaw.flatMap(FieldOrigin.init(rawValue:)) }
        set { createdByRaw = newValue?.rawValue }
    }

    var fieldProvenance: FieldProvenance {
        get { FieldProvenance.decode(from: fieldProvenanceJSON) }
        set { fieldProvenanceJSON = newValue.encode() }
    }

    init(
        id: UUID = UUID(),
        projectID: UUID? = nil,
        title: String,
        status: TaskStatus = .todo,
        priority: TaskPriority = .medium,
        ownerName: String? = nil,
        dueAt: Date? = nil,
        sourceItemID: UUID? = nil,
        sourceSegmentIDs: [String] = [],
        confidence: Double? = nil,
        notes: String? = nil,
        createdAt: Date = Date(),
        updatedAt: Date = Date()
    ) {
        self.id = id
        self.projectID = projectID
        self.title = title
        self.statusRaw = status.rawValue
        self.priorityRaw = priority.rawValue
        self.ownerName = ownerName
        self.dueAt = dueAt
        self.sourceItemID = sourceItemID
        self.sourceSegmentIDs = sourceSegmentIDs.isEmpty ? nil : (try? JSONEncoder().encode(sourceSegmentIDs)).flatMap { String(data: $0, encoding: .utf8) }
        self.confidence = confidence
        self.notes = notes
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.createdByRaw = nil
        self.fieldProvenanceJSON = nil
    }
}

// MARK: - TaskItem + FieldProvidence

extension TaskItem: FieldProvidence {
    var provenance: FieldProvenance {
        get { FieldProvenance.decode(from: fieldProvenanceJSON) }
        set { fieldProvenanceJSON = newValue.encode() }
    }

    func writeProvenance() {
        fieldProvenanceJSON = provenance.encode()
    }
}

enum TaskStatus: String, Codable, CaseIterable {
    case todo
    case inProgress
    case done
    case cancelled
}

enum TaskPriority: String, Codable, CaseIterable {
    case low
    case medium
    case high
    case critical
}

// MARK: - Person

@Model
final class Person {
    @Attribute(.unique) var id: UUID
    var displayName: String
    @Attribute(.unique) var canonicalKey: String
    var email: String?
    var role: String?
    var createdAt: Date

    init(
        id: UUID = UUID(),
        displayName: String,
        canonicalKey: String? = nil,
        email: String? = nil,
        role: String? = nil,
        createdAt: Date = Date()
    ) {
        self.id = id
        self.displayName = displayName
        self.canonicalKey = canonicalKey ?? displayName.lowercased().trimmingCharacters(in: .whitespaces)
        self.email = email
        self.role = role
        self.createdAt = createdAt
    }
}

// MARK: - GraphEdge

@Model
final class GraphEdge {
    @Attribute(.unique) var id: UUID
    var fromID: UUID
    var toID: UUID
    var edgeTypeRaw: String
    var weight: Double
    var provenanceItemID: UUID?
    var provenanceSegmentIDs: String?
    var createdAt: Date

    var edgeType: EdgeType {
        get { EdgeType(rawValue: edgeTypeRaw) ?? .relatesTo }
        set { edgeTypeRaw = newValue.rawValue }
    }

    var provenanceSegmentIDList: [String] {
        guard let json = provenanceSegmentIDs, let data = json.data(using: .utf8),
              let list = try? JSONDecoder().decode([String].self, from: data) else { return [] }
        return list
    }

    init(
        id: UUID = UUID(),
        fromID: UUID,
        toID: UUID,
        edgeType: EdgeType,
        weight: Double = 1.0,
        provenanceItemID: UUID? = nil,
        provenanceSegmentIDs: [String] = [],
        createdAt: Date = Date()
    ) {
        self.id = id
        self.fromID = fromID
        self.toID = toID
        self.edgeTypeRaw = edgeType.rawValue
        self.weight = weight
        self.provenanceItemID = provenanceItemID
        self.provenanceSegmentIDs = provenanceSegmentIDs.isEmpty ? nil : (try? JSONEncoder().encode(provenanceSegmentIDs)).flatMap { String(data: $0, encoding: .utf8) }
        self.createdAt = createdAt
    }
}

enum EdgeType: String, Codable, CaseIterable {
    case relatesTo
    case mentions
    case supports
    case assignedTo
    case blockedBy
    case belongsTo
    case produced
    case precedes
    case references
    case contradicts
}

// MARK: - Entity

@Model
final class Entity {
    @Attribute(.unique) var id: UUID
    var kindRaw: String
    var displayName: String
    @Attribute(.unique) var canonicalKey: String

    var kind: EntityKind {
        get { EntityKind(rawValue: kindRaw) ?? .other }
        set { kindRaw = newValue.rawValue }
    }

    init(
        id: UUID = UUID(),
        kind: EntityKind,
        displayName: String,
        canonicalKey: String? = nil
    ) {
        self.id = id
        self.kindRaw = kind.rawValue
        self.displayName = displayName
        self.canonicalKey = canonicalKey ?? "\(kind.rawValue):\(displayName.lowercased().trimmingCharacters(in: .whitespaces))"
    }
}

enum EntityKind: String, Codable, CaseIterable {
    case person
    case organization
    case system
    case repository
    case ticket
    case location
    case other
}

// MARK: - Project Framework (stored as JSON in Project.frameworkJSON)

struct ProjectFramework: Codable, Sendable {
    let id: String
    let name: String
    let description: String
    let itemAnalysis: AnalysisConfig
    let projectSynthesis: SynthesisConfig
    let views: [ViewDefinition]
    let entityKinds: [String]
    let edgeTypes: [String]
}

struct AnalysisConfig: Codable, Sendable {
    let systemPrompt: String
    let outputSchema: AnalysisOutputSchema
    let renderAs: [FieldRenderer]
}

struct AnalysisOutputSchema: Codable, Sendable {
    let type: String          // "object"
    let properties: [String: SchemaProperty]
    let required: [String]?
}

struct SchemaProperty: Codable, Sendable {
    let type: String          // "string", "array", "object"
    let items: SchemaItems?   // for array types
    let properties: [String: SchemaProperty]? // for object types
    let description: String?
}

struct SchemaItems: Codable, Sendable {
    let type: String
    let properties: [String: SchemaProperty]?

    init(type: String, properties: [String: SchemaProperty]? = nil) {
        self.type = type
        self.properties = properties
    }
}

struct SynthesisConfig: Codable, Sendable {
    let systemPrompt: String
    let outputSchema: AnalysisOutputSchema
}

struct FieldRenderer: Codable, Sendable {
    let field: String
    let type: RenderType
    let title: String
    let icon: String?
}

enum RenderType: String, Codable, Sendable {
    case card
    case list
    case table
    case markdown
    case chips
    case timeline
}

struct ViewDefinition: Codable, Sendable {
    let id: String
    let title: String
    let type: ViewType
    let source: String

    /// Validates that the view definition has a supported type and non-empty source.
    var isValid: Bool {
        let validSources: Set<String> = ["items", "tasks", "edges", "analysis.hypotheses", "analysis.findings", "analysis.ideas", "analysis.competencies", "analysis.cases", "analysis.stories", "tags", "entities"]
        return !source.isEmpty && validSources.contains(source)
    }
}

enum ViewType: String, Codable, Sendable {
    case list
    case kanban
    case timeline
    case graph
    case cards
    case table
    case markdown
    case chips
}

// MARK: - Lens (unified Framework + ai_config.json lenses)

enum LensCategory: String, Codable, Sendable, CaseIterable {
    case domain      // meeting, research, legal, product, coaching
    case analytical  // risk_analysis, executive_summary, design_critique
    case personal    // journal, brainstorm
    case custom
}

struct Lens: Codable, Sendable, Identifiable {
    var id: String
    var name: String
    var description: String
    var icon: String
    var category: LensCategory
    var framework: ProjectFramework?
    var systemPromptOverride: String?
    var userPromptTemplate: String?

    var hasFramework: Bool { framework != nil }
}

// MARK: - Preset

/// Exportable project behavior preset. Contains process, not data.
struct Preset: Codable, Sendable, Identifiable {
    var id: String
    var name: String
    var description: String
    var lensID: String?
    var frameworkJSON: String?
    var customInstructions: String?
    var markdownTemplates: [String: String]
    var analysisRules: [String]
    var doubtRules: [String]
    var relevanceCriteria: [String]
    var llmBehavior: String?
    var exportedAt: Date
    var version: Int

    init(id: String, name: String, description: String = "", lensID: String? = nil,
         frameworkJSON: String? = nil, customInstructions: String? = nil,
         markdownTemplates: [String: String] = [:], analysisRules: [String] = [],
         doubtRules: [String] = [], relevanceCriteria: [String] = [],
         llmBehavior: String? = nil, exportedAt: Date = Date(), version: Int = 1) {
        self.id = id; self.name = name; self.description = description
        self.lensID = lensID; self.frameworkJSON = frameworkJSON
        self.customInstructions = customInstructions
        self.markdownTemplates = markdownTemplates
        self.analysisRules = analysisRules; self.doubtRules = doubtRules
        self.relevanceCriteria = relevanceCriteria; self.llmBehavior = llmBehavior
        self.exportedAt = exportedAt; self.version = version
    }
}

// MARK: - ProjectFrame (Scope)

@Model
final class ProjectFrame {
    @Attribute(.unique) var id: UUID
    var projectID: UUID
    var parentFrameID: UUID?
    var name: String
    var lensID: String?
    // [String] is NOT supported as a direct SwiftData attribute — CoreData
    // cannot materialize "Array<String>". Store as JSON string instead.
    private var _filterTagsJSON: String = "[]"
    var filterDateStart: Date?
    var filterDateEnd: Date?
    private var _filterItemTypesJSON: String = "[]"
    var createdAt: Date

    var isRoot: Bool { parentFrameID == nil }

    @Transient
    var filterTags: [String] {
        get { Self.decodeJSONArray(_filterTagsJSON) }
        set { _filterTagsJSON = Self.encodeJSONArray(newValue) }
    }

    @Transient
    var filterItemTypes: [String] {
        get { Self.decodeJSONArray(_filterItemTypesJSON) }
        set { _filterItemTypesJSON = Self.encodeJSONArray(newValue) }
    }

    private static func decodeJSONArray(_ json: String) -> [String] {
        guard let data = json.data(using: .utf8),
              let result = try? JSONDecoder().decode([String].self, from: data) else {
            return []
        }
        return result
    }

    private static func encodeJSONArray(_ array: [String]) -> String {
        guard !array.isEmpty else { return "[]" }
        if let data = try? JSONEncoder().encode(array),
           let json = String(data: data, encoding: .utf8) {
            return json
        }
        return "[]"
    }

    /// Returns true if an item matches this frame's scope.
    func includes(itemType: String, createdAt itemDate: Date, tags itemTags: [String]) -> Bool {
        let itemTypes = filterItemTypes
        if !itemTypes.isEmpty, !itemTypes.contains(itemType) { return false }
        if let start = filterDateStart, itemDate < start { return false }
        if let end = filterDateEnd, itemDate > end { return false }
        let tags = filterTags
        if !tags.isEmpty {
            let hasTag = tags.contains(where: { t in itemTags.contains { $0.localizedCaseInsensitiveCompare(t) == .orderedSame } })
            if !hasTag { return false }
        }
        return true
    }

    init(id: UUID = UUID(), projectID: UUID, parentFrameID: UUID? = nil, name: String,
         lensID: String? = nil, filterTags: [String] = [], filterDateStart: Date? = nil,
         filterDateEnd: Date? = nil, filterItemTypes: [String] = []) {
        self.id = id; self.projectID = projectID; self.parentFrameID = parentFrameID
        self.name = name; self.lensID = lensID
        self._filterTagsJSON = Self.encodeJSONArray(filterTags)
        self.filterDateStart = filterDateStart; self.filterDateEnd = filterDateEnd
        self._filterItemTypesJSON = Self.encodeJSONArray(filterItemTypes)
        self.createdAt = Date()
    }
}

// MARK: - Versioning

enum SnapshotTrigger: String, Codable, CaseIterable, Sendable {
    case manual
    case auto_ingestion
    case auto_milestone
}

/// Individual field change record. The atom of version history.
@Model
final class ChangeRecord {
    @Attribute(.unique) var id: UUID
    var entityType: String
    var entityID: UUID
    var projectID: UUID?
    var field: String
    var previousValue: String?
    var newValue: String?
    var originRaw: String
    var timestamp: Date
    var snapshotID: UUID?

    var origin: FieldOrigin {
        get { FieldOrigin(rawValue: originRaw) ?? .llm }
        set { originRaw = newValue.rawValue }
    }

    init(id: UUID = UUID(), entityType: String, entityID: UUID, projectID: UUID? = nil,
         field: String, previousValue: String? = nil, newValue: String? = nil,
         origin: FieldOrigin = .llm, timestamp: Date = Date(), snapshotID: UUID? = nil) {
        self.id = id; self.entityType = entityType; self.entityID = entityID
        self.projectID = projectID; self.field = field
        self.previousValue = previousValue; self.newValue = newValue
        self.originRaw = origin.rawValue; self.timestamp = timestamp; self.snapshotID = snapshotID
    }
}

/// A point-in-time snapshot of a project's state.
@Model
final class ProjectSnapshot {
    @Attribute(.unique) var id: UUID
    var projectID: UUID
    var label: String?
    var triggerRaw: String
    var createdAt: Date
    var changeCount: Int
    var summary: String?

    var trigger: SnapshotTrigger {
        get { SnapshotTrigger(rawValue: triggerRaw) ?? .manual }
        set { triggerRaw = newValue.rawValue }
    }

    init(id: UUID = UUID(), projectID: UUID, label: String? = nil,
         trigger: SnapshotTrigger = .manual, createdAt: Date = Date(),
         changeCount: Int = 0, summary: String? = nil) {
        self.id = id; self.projectID = projectID; self.label = label
        self.triggerRaw = trigger.rawValue; self.createdAt = createdAt
        self.changeCount = changeCount; self.summary = summary
    }
}

// MARK: - Agent Suggestion (Signal System)

/// The "atom of attention" — a signal raised by the system or LLM.
/// Types: risk, alert, opportunity, change, contradiction, pattern, doubt, new_project, emerging_problem,
///        task, edge, annotation, decision, field_change.
/// Status lifecycle: visible → seen → (acknowledged|approved|rejected|archived|auto_archived|transformed|ignored)
@Model
final class AgentSuggestion {
    @Attribute(.unique) var id: UUID
    var projectID: UUID?
    var type: String
    var title: String
    var body: String?
    var status: String
    var confidence: Double?
    var sourceItemID: UUID?
    var sourceSegmentIDs: String?  // JSON array
    var payloadJSON: String?       // JSON for the actual action
    var createdAt: Date
    var resolvedAt: Date?

    // Contextual priority scores (0-1)
    var impactScore: Double?
    var urgencyScore: Double?
    var relevanceScore: Double?

    // Resolution tracking
    var resolutionReason: String?
    var resolvedByRaw: String?
    var isCritical: Bool

    init(id: UUID = UUID(), projectID: UUID? = nil, type: String, title: String,
         body: String? = nil, status: String = "visible", confidence: Double? = nil,
         sourceItemID: UUID? = nil, sourceSegmentIDs: [String]? = nil,
         payloadJSON: String? = nil, createdAt: Date = Date(), resolvedAt: Date? = nil,
         impactScore: Double? = nil, urgencyScore: Double? = nil, relevanceScore: Double? = nil,
         resolutionReason: String? = nil, resolvedByRaw: String? = nil, isCritical: Bool = false) {
        self.id = id; self.projectID = projectID; self.type = type; self.title = title
        self.body = body; self.status = status; self.confidence = confidence
        self.sourceItemID = sourceItemID
        self.sourceSegmentIDs = sourceSegmentIDs.flatMap { try? JSONEncoder().encode($0) }.flatMap { String(data: $0, encoding: .utf8) }
        self.payloadJSON = payloadJSON; self.createdAt = createdAt; self.resolvedAt = resolvedAt
        self.impactScore = impactScore; self.urgencyScore = urgencyScore; self.relevanceScore = relevanceScore
        self.resolutionReason = resolutionReason; self.resolvedByRaw = resolvedByRaw; self.isCritical = isCritical
    }

    /// Computed contextual priority (0-100). Uses stored scores or falls back to confidence.
    var computedPriority: Double {
        let impact = impactScore ?? 0.5
        let urgency = urgencyScore ?? 0.5
        let relevance = relevanceScore ?? 0.5
        let base = (impact * 0.4 + urgency * 0.35 + relevance * 0.25) * 100
        // Age decay: signals older than 7 days lose up to 30% priority
        let ageDays = Date().timeIntervalSince(createdAt) / 86400
        let decay = min(ageDays / 7.0 * 0.3, 0.3)
        return max(base * (1.0 - decay), 5.0)
    }

    /// Whether this signal is in an active (unresolved) state.
    var isActive: Bool {
        ["visible", "seen", "acknowledged"].contains(status)
    }
}

// MARK: - Queue Entry (Processing Queue)

/// Persisted job in the processing queue. Survives app kills via SwiftData.
@Model
final class QueueEntry {
    @Attribute(.unique) var id: UUID
    var itemID: UUID
    var projectID: UUID?
    var statusRaw: String
    var priority: Int
    var queuedAt: Date
    var startedAt: Date?
    var completedAt: Date?
    var retryCount: Int
    var maxRetries: Int
    var lastError: String?
    var position: Int

    var status: QueueStatus {
        get { QueueStatus(rawValue: statusRaw) ?? .queued }
        set { statusRaw = newValue.rawValue }
    }

    init(
        id: UUID = UUID(),
        itemID: UUID,
        projectID: UUID? = nil,
        status: QueueStatus = .queued,
        priority: Int = 50,
        queuedAt: Date = Date(),
        startedAt: Date? = nil,
        completedAt: Date? = nil,
        retryCount: Int = 0,
        maxRetries: Int = 2,
        lastError: String? = nil,
        position: Int = 0
    ) {
        self.id = id
        self.itemID = itemID
        self.projectID = projectID
        self.statusRaw = status.rawValue
        self.priority = priority
        self.queuedAt = queuedAt
        self.startedAt = startedAt
        self.completedAt = completedAt
        self.retryCount = retryCount
        self.maxRetries = maxRetries
        self.lastError = lastError
        self.position = position
    }
}

enum QueueStatus: String, Codable, CaseIterable, Sendable {
    case queued
    case processing
    case paused
    case done
    case failed
    case cancelled
    case waitingForUser = "waiting_for_user"
}

