import Foundation
import OSLog

/// Maps anarlog Jinja2 templates ↔ Wawa Note PromptStore editable prompts.
///
/// anarlog templates are Askama/Jinja2 files (`.md.jinja`) with:
/// - `{{ variable }}` interpolation
/// - `{% if condition %}` / `{% endif %}` blocks
/// - `{% for item in list %}` / `{% endfor %}` loops
/// - `{%- import "_macros.jinja" as macros -%}` includes
///
/// Wawa Note uses simpler `{variable}` placeholders in editable prompts.
///
/// The mapper:
/// 1. Imports anarlog templates into PromptStore with variables translated
/// 2. Exports PromptStore prompts back to Jinja2 format for use in anarlog desktop
@MainActor
enum TemplateMapper {
    private static let logger = Logger(subsystem: "com.wawa.note", category: "TemplateMapper")

    // MARK: - Known anarlog templates

    /// Known anarlog template files and their Wawa Note equivalents.
    static let templateMap: [(jinjaFile: String, wawaPromptName: String, category: String)] = [
        ("enhance.system.md.jinja", "analysis_system", "analysis"),
        ("enhance.user.md.jinja", "analysis_user", "analysis"),
        ("title.system.md.jinja", "title_system", "analysis"),
        ("title.user.md.jinja", "title_user", "analysis"),
        ("daily-summary.system.md.jinja", "daily_summary_system", "analysis"),
        ("daily-summary.user.md.jinja", "daily_summary_user", "analysis"),
        ("event-contact.system.md.jinja", "event_contact_system", "analysis"),
        ("event-contact.user.md.jinja", "event_contact_user", "analysis"),
        ("activity-capture.system.md.jinja", "activity_capture_system", "custom"),
        ("activity-capture.user.md.jinja", "activity_capture_user", "custom"),
        ("chat.system.md.jinja", "chat_system", "chat"),
        ("context.block.md.jinja", "context_block", "chat"),
    ]

    // MARK: - Import from anarlog

    /// Import a single Jinja2 template string into a Wawa Note EditablePrompt.
    static func importTemplate(jinjaContent: String, name: String, category: String) -> EditablePrompt {
        let variables = extractJinjaVariables(jinjaContent)
        let wawaContent = translateJinjaToWawa(jinjaContent)

        return EditablePrompt(
            name: name,
            category: category,
            content: wawaContent,
            description: "Imported from anarlog template",
            variables: variables,
            updatedAt: Date(),
            isUserEdited: false
        )
    }

    /// Import a template file from an anarlog templates directory.
    static func importTemplateFile(at url: URL, promptStore: PromptStore) -> String? {
        guard let content = try? String(contentsOf: url, encoding: .utf8) else {
            logger.warning("Cannot read template: \(url.lastPathComponent)")
            return nil
        }

        let filename = url.lastPathComponent
        guard let mapping = templateMap.first(where: { $0.jinjaFile == filename }) else {
            logger.info("Unknown anarlog template: \(filename), skipping")
            return nil
        }

        let prompt = importTemplate(
            jinjaContent: content,
            name: mapping.wawaPromptName,
            category: mapping.category
        )

        // Store in PromptStore
        if promptStore.prompt(named: mapping.wawaPromptName) == nil {
            _ = promptStore.createPrompt(
                name: mapping.wawaPromptName,
                category: mapping.category,
                content: prompt.content,
                description: prompt.description
            )
        } else {
            promptStore.updatePrompt(named: mapping.wawaPromptName, content: prompt.content)
        }

        logger.info("Imported anarlog template: \(filename) → \(mapping.wawaPromptName)")
        return mapping.wawaPromptName
    }

    /// Import all templates from a directory.
    static func importAllTemplates(from directoryURL: URL, promptStore: PromptStore) -> [String] {
        guard
            let files = try? FileManager.default.contentsOfDirectory(
                at: directoryURL,
                includingPropertiesForKeys: nil,
                options: .skipsHiddenFiles
            ).filter({ $0.pathExtension == "jinja" })
        else {
            return []
        }
        return files.compactMap { importTemplateFile(at: $0, promptStore: promptStore) }
    }

    // MARK: - Export to anarlog

    /// Convert a Wawa Note prompt back to Jinja2 format.
    static func exportAsJinja(prompt: EditablePrompt, originalFilename: String?) -> String {
        let content = translateWawaToJinja(prompt.content)
        // Add a header comment
        var output = "{# Generated by Wawa Note — \(prompt.name) #}\n"
        output += "{# Category: \(prompt.category) | Variables: \(prompt.variables.joined(separator: ", ")) #}\n\n"
        output += content
        return output
    }

    /// Export all user-edited prompts matching anarlog templates.
    static func exportAllTemplates(promptStore: PromptStore, to directoryURL: URL) throws -> [URL] {
        try FileManager.default.createDirectory(at: directoryURL, withIntermediateDirectories: true)
        var exported: [URL] = []

        for mapping in templateMap {
            guard let prompt = promptStore.prompt(named: mapping.wawaPromptName),
                prompt.isUserEdited
            else { continue }

            let jinja = exportAsJinja(prompt: prompt, originalFilename: mapping.jinjaFile)
            let fileURL = directoryURL.appendingPathComponent(mapping.jinjaFile)
            try jinja.write(to: fileURL, atomically: true, encoding: .utf8)
            exported.append(fileURL)
        }

        return exported
    }

    // MARK: - Variable extraction

    /// Extract Jinja2 variable references from a template string.
    /// Handles `{{ variable }}`, `{{ obj.field }}`, `{{ obj.method() }}`.
    static func extractJinjaVariables(_ template: String) -> [String] {
        let pattern = #"\{\{\s*([^}]+?)\s*\}\}"#
        guard let regex = try? NSRegularExpression(pattern: pattern) else { return [] }

        let range = NSRange(template.startIndex..., in: template)
        let matches = regex.matches(in: template, range: range)

        var variables = Set<String>()
        for match in matches {
            guard let captureRange = Range(match.range(at: 1), in: template) else { continue }
            let expr = String(template[captureRange]).trimmingCharacters(in: .whitespaces)

            // Extract top-level variable name
            // "session.title" → "session_title"
            // "language | language" → "language"
            // "transcripts | length" → "transcripts"
            let parts = expr.components(separatedBy: "|")
            let varPart = parts[0].trimmingCharacters(in: .whitespaces)
            let cleanName =
                varPart
                .replacingOccurrences(of: ".", with: "_")
                .replacingOccurrences(of: "()", with: "")
                .trimmingCharacters(in: .whitespaces)

            variables.insert(cleanName)
        }

        return variables.sorted()
    }

    // MARK: - Jinja2 → Wawa translation

    /// Translate Jinja2 template syntax to Wawa Note format.
    /// Replaces `{{ var }}` with `{var}`, simplifies control flow to comments.
    static func translateJinjaToWawa(_ jinja: String) -> String {
        var result = jinja

        // Replace `{{ variable }}` → `{variable}`
        let varPattern = #"\{\{\s*([^}]+?)\s*\}\}"#
        result = result.replacingOccurrences(of: varPattern, with: "{$1}", options: .regularExpression)

        // Simplify `{% if ... %}` blocks → keep content, add context comment
        // We can't fully translate control flow, so we preserve the content
        let ifPattern = #"\{%-?\s*if\s+([^%]+?)\s*-?%\}"#
        result = result.replacingOccurrences(of: ifPattern, with: "<!-- anarlog: if $1 -->", options: .regularExpression)

        let endifPattern = #"\{%-?\s*endif\s*-?%\}"#
        result = result.replacingOccurrences(of: endifPattern, with: "<!-- /anarlog: endif -->", options: .regularExpression)

        // Simplify `{% for ... %}` / `{% endfor %}`
        let forPattern = #"\{%-?\s*for\s+([^%]+?)\s*-?%\}"#
        result = result.replacingOccurrences(of: forPattern, with: "<!-- anarlog: for $1 -->", options: .regularExpression)

        let endforPattern = #"\{%-?\s*endfor\s*-?%\}"#
        result = result.replacingOccurrences(of: endforPattern, with: "<!-- /anarlog: endfor -->", options: .regularExpression)

        // Simplify `{% match ... %}` / `{% when ... %}`
        let matchPattern = #"\{%-?\s*match\s+([^%]+?)\s*-?%\}"#
        result = result.replacingOccurrences(of: matchPattern, with: "<!-- anarlog: match $1 -->", options: .regularExpression)

        let whenPattern = #"\{%-?\s*when\s+([^%]+?)\s*-?%\}"#
        result = result.replacingOccurrences(of: whenPattern, with: "<!-- anarlog: when $1 -->", options: .regularExpression)

        let endmatchPattern = #"\{%-?\s*endmatch\s*-?%\}"#
        result = result.replacingOccurrences(of: endmatchPattern, with: "<!-- /anarlog: endmatch -->", options: .regularExpression)

        // Remove `{% import ... %}` — replaced by native include
        let importPattern = #"\{%-?\s*import\s+[^%]+\s*-?%\}\s*\n?"#
        result = result.replacingOccurrences(of: importPattern, with: "", options: .regularExpression)

        // Clean up extra blank lines from removed blocks
        result = result.replacingOccurrences(of: "\n\n\n", with: "\n\n")

        return result
    }

    // MARK: - Wawa → Jinja2 translation

    /// Translate Wawa Note format back to Jinja2 (best effort).
    static func translateWawaToJinja(_ wawa: String) -> String {
        var result = wawa

        // HTML comments that were Jinja2 structures → restore
        let ifRestore = #"<!-- anarlog: if ([^>]+) -->"#
        result = result.replacingOccurrences(of: ifRestore, with: "{% if $1 %}", options: .regularExpression)

        let endifRestore = #"<!-- /anarlog: endif -->"#
        result = result.replacingOccurrences(of: endifRestore, with: "{% endif %}", options: .regularExpression)

        let forRestore = #"<!-- anarlog: for ([^>]+) -->"#
        result = result.replacingOccurrences(of: forRestore, with: "{% for $1 %}", options: .regularExpression)

        let endforRestore = #"<!-- /anarlog: endfor -->"#
        result = result.replacingOccurrences(of: endforRestore, with: "{% endfor %}", options: .regularExpression)

        // Replace `{variable}` → `{{ variable }}` (only those that aren't in HTML comments)
        let varRestore = #"\{([a-z_][a-z0-9_.]*)\}"#
        result = result.replacingOccurrences(of: varRestore, with: "{{ $1 }}", options: .regularExpression)

        return result
    }
}
