import Foundation
import SwiftData

/// Manages the special wawa-note-config project that contains all app configuration as editable files.
/// This project is auto-created on first launch and hidden from regular project lists.
@MainActor
final class ConfigProjectService {
    static let configProjectName = "Wawa Note Config"
    static let configProjectSlug = "wawa-note-config"

    private init() {}

    /// Returns the config project, creating it if it doesn't exist.
    static func ensureConfigProject(context: ModelContext) -> Project {
        if let existing = findConfigProject(context: context) {
            return existing
        }
        return createConfigProject(context: context)
    }

    /// Whether a project is the config project.
    static func isConfigProject(_ project: Project) -> Bool {
        project.slug == configProjectSlug
    }

    /// Whether a project slug is the config project.
    static func isConfigProjectSlug(_ slug: String) -> Bool {
        slug == configProjectSlug
    }

    // MARK: - Private

    private static func findConfigProject(context: ModelContext) -> Project? {
        let predicate = #Predicate<Project> { $0.slug == configProjectSlug }
        let descriptor = FetchDescriptor<Project>(predicate: predicate)
        return try? context.fetch(descriptor).first
    }

    private static func createConfigProject(context: ModelContext) -> Project {
        let svc = ProjectService(context: context)
        guard let project = try? svc.create(
            name: configProjectName,
            summary: "App configuration: providers, prompts, settings, and agent memories. Edit files directly to customize Wawa Note."
        ) else {
            fatalError("ConfigProjectService: failed to create config project")
        }
        // Override the auto-generated slug to ensure it's always wawa-note-config
        project.slug = configProjectSlug
        project.iconName = "gearshape.fill"
        project.colorHex = "#64748B" // slate gray — neutral, distinct from user projects
        project.intention = "System configuration project. Contains AI providers, prompt templates, app settings, and agent memories."
        project.intentionIsAutoGenerated = true
        try? context.save()
        AppLog.event("config", "Created wawa-note-config project")
        return project
    }

    // MARK: - Population

    /// Populate the config project with sub-items for each configuration category.
    /// Only runs if the project has no items yet (first launch after creation).
    static func populateIfEmpty(context: ModelContext) {
        guard let project = findConfigProject(context: context) else { return }
        let psvc = ProjectService(context: context)
        let existingItems = (try? psvc.items(in: project.id)) ?? []
        guard existingItems.isEmpty else { return }

        let isvc = KnowledgeItemService(context: context)

        // 1. Providers — one item per AI provider
        let configs = (try? context.fetch(FetchDescriptor<AIProviderConfigModel>())) ?? []
        for config in configs {
            let dict: [String: Any] = [
                "name": config.name, "type": config.typeRaw,
                "defaultModel": config.defaultModel,
                "baseURL": config.baseURLString as Any,
                "supportsStreaming": config.supportsStreaming,
                "supportsTools": config.supportsTools
            ]
            let json = (try? JSONSerialization.data(withJSONObject: dict, options: .prettyPrinted))
                .flatMap { String(data: $0, encoding: .utf8) } ?? "{}"
            if let item = try? isvc.createItem(type: .note, title: "Provider: \(config.name)",
                bodyText: json, tags: ["config", "provider"], inboxDate: nil) {
                try? psvc.addItem(item.id, to: project.id)
            }
        }

        // 2. Prompts — one item per prompt template
        let prompts = PromptStore.shared.prompts(in: nil)
        for prompt in prompts {
            if let item = try? isvc.createItem(type: .note, title: "Prompt: \(prompt.name)",
                bodyText: prompt.content, tags: ["config", "prompt"], inboxDate: nil) {
                try? psvc.addItem(item.id, to: project.id)
            }
        }

        // 3. Settings — one item with app preferences
        let settingsDict: [String: Any] = [
            "automation": AutomationSettings.shared.autoAnalyze,
            "appVersion": Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String ?? "unknown",
            "buildNumber": Bundle.main.infoDictionary?["CFBundleVersion"] as? String ?? "unknown"
        ]
        let settingsJSON = (try? JSONSerialization.data(withJSONObject: settingsDict, options: .prettyPrinted))
            .flatMap { String(data: $0, encoding: .utf8) } ?? "{}"
        if let item = try? isvc.createItem(type: .note, title: "App Settings",
            bodyText: settingsJSON, tags: ["config", "settings"], inboxDate: nil) {
            try? psvc.addItem(item.id, to: project.id)
        }

        // 4. Memories — one item as JSON
        let memories = AgentMemoryStore.shared.listAll()
        if !memories.isEmpty,
           let data = try? JSONEncoder().encode(memories),
           let json = String(data: data, encoding: .utf8),
           let item = try? isvc.createItem(type: .note, title: "Agent Memories",
            bodyText: json, tags: ["config", "memories"], inboxDate: nil) {
            try? psvc.addItem(item.id, to: project.id)
        }

        try? context.save()
        AppLog.event("config", "Populated wawa-note-config with \(existingItems.count) items")
    }
}
