import Foundation
import SwiftData

/// Manages the special wawa-note-config project that contains all app configuration as editable files.
/// This project is auto-created on first launch and hidden from regular project lists.
@MainActor
final class ConfigProjectService {
    static let configProjectName = "Wawa Note Config"
    static let configProjectSlug = "wawa-note-config"

    private init() {}

    /// Returns the config project, creating it if it doesn't exist.
    static func ensureConfigProject(context: ModelContext) -> Project {
        if let existing = findConfigProject(context: context) {
            return existing
        }
        return createConfigProject(context: context)
    }

    /// Whether a project is the config project.
    static func isConfigProject(_ project: Project) -> Bool {
        project.slug == configProjectSlug
    }

    /// Whether a project slug is the config project.
    static func isConfigProjectSlug(_ slug: String) -> Bool {
        slug == configProjectSlug
    }

    // MARK: - Private

    private static func findConfigProject(context: ModelContext) -> Project? {
        let predicate = #Predicate<Project> { $0.slug == configProjectSlug }
        let descriptor = FetchDescriptor<Project>(predicate: predicate)
        return try? context.fetch(descriptor).first
    }

    private static func createConfigProject(context: ModelContext) -> Project {
        let svc = ProjectService(context: context)
        let project: Project
        do {
            project = try svc.create(
                name: configProjectName,
                summary: "App configuration: providers, prompts, settings, and agent memories. Edit files directly to customize Wawa Note."
            )
        } catch {
            AppLog.general.error("ConfigProjectService: failed to create config project — \(error.localizedDescription)")
            fatalError("ConfigProjectService: failed to create config project: \(error.localizedDescription)")
        }
        // Override the auto-generated slug to ensure it's always wawa-note-config
        project.slug = configProjectSlug
        project.iconName = "gearshape.fill"
        project.colorHex = "#64748B" // slate gray — neutral, distinct from user projects
        project.intention = "System configuration project. Contains AI providers, prompt templates, app settings, and agent memories."
        project.intentionIsAutoGenerated = true
        try? context.save()
        AppLog.event("config", "Created wawa-note-config project")
        return project
        return project
    }

    // MARK: - Sync

    /// Sync the config project items with the current app state.
    /// Unlike populateIfEmpty (one-shot), this runs every launch to keep items current.
    static func syncConfigProject(context: ModelContext) {
        guard let project = findConfigProject(context: context) else { return }
        let psvc = ProjectService(context: context)

        // Remove all existing auto-generated config items (batch: detach + mark for delete)
        let existing = (try? psvc.items(in: project.id)) ?? []
        let toRemove = existing.filter { item in
            item.title.hasPrefix("Provider: ") ||
            item.title.hasPrefix("Prompt: ") ||
            item.title == "App Settings" ||
            item.title == "Agent Memories"
        }
        for item in toRemove {
            item.projectID = nil // detach from project
            context.delete(item) // mark for deletion
        }

        // Helper: create item directly without intermediate saves
        func makeItem(title: String, body: String, tags: [String]) -> KnowledgeItem {
            let item = KnowledgeItem(type: .note, title: title, status: .draft,
                tags: tags, folderID: nil, bodyText: body,
                durationSeconds: nil, languageCode: nil, inboxDate: nil)
            context.insert(item)
            item.projectID = project.id
            return item
        }

        // 1. Providers
        let configs = (try? context.fetch(FetchDescriptor<AIProviderConfigModel>())) ?? []
        for config in configs {
            let dict: [String: Any] = [
                "name": config.name, "type": config.typeRaw,
                "defaultModel": config.defaultModel,
                "baseURL": config.baseURLString as Any,
                "supportsStreaming": config.supportsStreaming,
                "supportsTools": config.supportsTools,
                "supportsAudio": config.supportsAudio,
                "supportsEmbeddings": config.supportsEmbeddings
            ]
            let json = (try? JSONSerialization.data(withJSONObject: dict, options: .prettyPrinted))
                .flatMap { String(data: $0, encoding: .utf8) } ?? "{}"
            _ = makeItem(title: "Provider: \(config.name)", body: json, tags: ["config", "provider"])
        }

        // 2. Prompts
        let prompts = PromptStore.shared.prompts(in: nil)
        for prompt in prompts {
            let meta: [String: Any] = [
                "name": prompt.name, "category": prompt.category,
                "isUserEdited": prompt.isUserEdited,
                "variables": prompt.variables
            ]
            let metaJSON = (try? JSONSerialization.data(withJSONObject: meta, options: .prettyPrinted))
                .flatMap { String(data: $0, encoding: .utf8) } ?? "{}"
            _ = makeItem(title: "Prompt: \(prompt.name)", body: "# Metadata\n\(metaJSON)\n\n# Content\n\(prompt.content)", tags: ["config", "prompt"])
        }

        // 3. Settings
        let settingsDict = buildSettingsSnapshot()
        let settingsJSON = (try? JSONSerialization.data(withJSONObject: settingsDict, options: .prettyPrinted))
            .flatMap { String(data: $0, encoding: .utf8) } ?? "{}"
        _ = makeItem(title: "App Settings", body: settingsJSON, tags: ["config", "settings"])

        // 4. Memories
        let memories = AgentMemoryStore.shared.listAll()
        if !memories.isEmpty,
           let data = try? JSONEncoder().encode(memories),
           let json = String(data: data, encoding: .utf8) {
            _ = makeItem(title: "Agent Memories", body: json, tags: ["config", "memories"])
        }

        // Single save
        try? context.save()
        AppLog.event("config", "Synced wawa-note-config: \(configs.count) providers, \(prompts.count) prompts, settings, \(memories.count) memories")
    }

    /// Build a complete settings snapshot from all UserDefaults and app state.
    static func buildSettingsSnapshot() -> [String: Any] {
        let defs = UserDefaults.standard
        var s: [String: Any] = [:]

        // App info
        s["appVersion"] = Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String ?? "unknown"
        s["buildNumber"] = Bundle.main.infoDictionary?["CFBundleVersion"] as? String ?? "unknown"

        // Transcription
        s["transcriptionMode"] = defs.string(forKey: "transcription_mode") ?? "apple"
        s["transcriptionAllowCloud"] = defs.bool(forKey: "transcription_allow_cloud")

        // Automation
        s["autoTranscribe"] = defs.object(forKey: "automation_auto_transcribe") as? Bool ?? true
        s["autoAnalyze"] = defs.object(forKey: "automation_auto_analyze") as? Bool ?? true
        s["autoAnalysisModel"] = defs.string(forKey: "automation_auto_analysis_model") ?? "gpt-5-nano"
        s["autoAnalysisProvider"] = defs.string(forKey: "automation_auto_analysis_provider") ?? "openAI"

        // Audio
        s["voiceProcessing"] = !defs.bool(forKey: "audio_raw_mode")
        s["speakerphoneMode"] = defs.bool(forKey: "audio_speakerphone_mode")

        // Developer
        s["developerModeEnabled"] = defs.bool(forKey: "developer_mode_enabled")

        // Active provider
        s["activeProviderId"] = defs.string(forKey: "active_provider_id") ?? "none"

        // Anarlog
        s["anarlogAutoImport"] = defs.object(forKey: "anarlog_auto_import") as? Bool ?? true
        s["anarlogAutoExport"] = defs.object(forKey: "anarlog_auto_export") as? Bool ?? false

        // AI Config summary
        let aiCfg = AIConfigService.shared.config
        s["aiProviders"] = Array(aiCfg.providers.keys)
        s["aiFeatures"] = aiCfg.features.map { Array($0.keys) } ?? []
        s["aiModelPresets"] = aiCfg.modelPresets?.count ?? 0
        s["aiLenses"] = aiCfg.lenses.map { Array($0.keys) } ?? []

        // Summary cache stats
        let cacheStats = SummaryCache.shared.stats
        s["summaryCacheEntries"] = cacheStats.entries
        s["summaryCacheHitRate"] = String(format: "%.1f%%", cacheStats.hitRate * 100)

        return s
    }
}
