import Foundation
import SwiftData

@MainActor
final class ProjectService {
  private let context: ModelContext

  init(context: ModelContext) {
    self.context = context
  }

  func create(name: String, summary: String? = nil, iconName: String? = nil) throws -> Project {
    let project = Project(name: name, summary: summary, colorHex: assignColor(), iconName: iconName)
    context.insert(project)
    try context.save()
    return project
  }

  func setColor(_ projectID: UUID, hex: String) throws {
    guard let project = try fetch(id: projectID) else { return }
    project.colorHex = hex
    try context.save()
  }

  func colorsForItems(_ items: [KnowledgeItem]) -> [UUID: String] {
    var result: [UUID: String] = [:]
    let projectIDs = Set(items.compactMap(\.projectID))
    for pid in projectIDs {
      if let project = try? fetch(id: pid), let hex = project.colorHex {
        result[pid] = hex
      }
    }
    return result
  }

  // MARK: - Private

  /// One-time: assign palette colors to all projects with nil colorHex.
  static func migrateProjectColors(context: ModelContext) {
    let service = ProjectService(context: context)
    guard let all = try? service.allProjects() else { return }
    let needColor = all.filter { $0.colorHex == nil }
    guard !needColor.isEmpty else { return }
    for project in needColor {
      project.colorHex = service.assignColor()
    }
    try? context.save()
  }

  /// One-time migration: set defaults for field provenance and task ownership.
  static func migrateFieldProvenance(context: ModelContext) {
    let key = "migration_field_provenance_v1"
    if UserDefaults.standard.bool(forKey: key) { return }

    // Existing tasks: default to user-created (safe — LLM won't delete pre-existing tasks)
    if let allTasks = try? context.fetch(FetchDescriptor<TaskItem>()) {
      for task in allTasks where task.createdByRaw == nil {
        task.createdBy = .user
        // Mark key fields as user-originated
        var prov = task.provenance
        prov.mark(field: "title", origin: .user)
        prov.mark(field: "status", origin: .user)
        prov.mark(field: "priority", origin: .user)
        if task.ownerName != nil { prov.mark(field: "ownerName", origin: .user) }
        if task.dueAt != nil { prov.mark(field: "dueAt", origin: .user) }
        task.fieldProvenanceJSON = prov.encode()
      }
    }

    // Existing projects: names are user-set (not auto-generated)
    if let allProjects = try? context.fetch(FetchDescriptor<Project>()) {
      for project in allProjects {
        let expectedSlug = project.name.lowercased().replacingOccurrences(of: " ", with: "-")
        project.nameIsAutoGenerated = (project.slug != expectedSlug)
      }
    }

    try? context.save()
    UserDefaults.standard.set(true, forKey: key)
  }

  /// One-time migration: convert TaskItem and AgentSuggestion records to ProjectDerivedItem.
  /// Converts all TaskItem records -> ProjectDerivedItem(type: .task) with TaskBody JSON.
  /// Converts all AgentSuggestion records -> ProjectDerivedItem(type: .signal) with SignalBody JSON.
  /// Uses UserDefaults flag "migration_to_project_derived_v1" to run once.
  /// Each conversion is wrapped in do/catch for resilience.
  /// Directly inserts ProjectDerivedItem instances (bypasses service layer) to avoid
  /// edge-creation during migration.
  static func migrateToProjectDerivedItems(context: ModelContext) {
    let key = "migration_to_project_derived_v1"
    if UserDefaults.standard.bool(forKey: key) { return }

    // Migrate TaskItems
    let allTasks: [TaskItem]
    do {
      allTasks = try context.fetch(FetchDescriptor<TaskItem>())
    } catch {
      AppLog.general.error("Migration: failed to fetch TaskItems: \(error)")
      return
    }
    for task in allTasks {
      guard let pid = task.projectID else { continue }

      // Check if already migrated (defensive dedup alongside UserDefaults guard)
      let taskTitle = task.title
      let existing = try? context.fetch(
        FetchDescriptor<ProjectDerivedItem>(
          predicate: #Predicate {
            $0.projectID == pid && $0.typeRaw == "task" && $0.title == taskTitle
          }
        )
      )
      if let existing, !existing.isEmpty { continue }

      do {
        let body = TaskBody(
          description: task.notes,
          sourceSegmentIDs: task.sourceSegmentIDList,
          aiGenerated: task.createdBy != .user,
          suggestedByItemID: task.sourceItemID
        )
        let bodyData = try? JSONEncoder().encode(body)
        let bodyStr = bodyData.flatMap { String(data: $0, encoding: .utf8) }

        let item = ProjectDerivedItem(
          projectID: pid,
          sourceItemID: task.sourceItemID,
          type: .task,
          title: task.title,
          bodyJSON: bodyStr,
          status: ProjectDerivedStatus(rawValue: task.statusRaw),
          priority: TaskPriority(rawValue: task.priorityRaw),
          ownerName: task.ownerName,
          dueAt: task.dueAt,
          confidence: task.confidence,
          createdAt: task.createdAt,
          updatedAt: task.updatedAt
        )
        context.insert(item)
      } catch {
        AppLog.general.error("Migration: failed to migrate task \(task.title): \(error)")
      }
    }

    // Migrate AgentSuggestions
    let allSignals: [AgentSuggestion]
    do {
      allSignals = try context.fetch(FetchDescriptor<AgentSuggestion>())
    } catch {
      AppLog.general.error("Migration: failed to fetch AgentSuggestions: \(error)")
      return
    }
    for signal in allSignals {
      guard let pid = signal.projectID else { continue }

      // Check if already migrated (defensive dedup alongside UserDefaults guard)
      let signalTitle = signal.title
      let existing = try? context.fetch(
        FetchDescriptor<ProjectDerivedItem>(
          predicate: #Predicate {
            $0.projectID == pid && $0.typeRaw == "signal" && $0.title == signalTitle
          }
        )
      )
      if let existing, !existing.isEmpty { continue }

      do {
        let body = SignalBody(
          signalType: signal.type,
          description: signal.body ?? "",
          suggestedAction: nil,
          impactScore: signal.impactScore,
          urgencyScore: signal.urgencyScore
        )
        let bodyData = try? JSONEncoder().encode(body)
        let bodyStr = bodyData.flatMap { String(data: $0, encoding: .utf8) }

        let derivedStatus: ProjectDerivedStatus = {
          switch signal.status {
          case "visible": return .visible
          case "seen", "acknowledged": return .acknowledged
          case "approved", "transformed": return .resolved
          default: return .dismissed
          }
        }()

        let item = ProjectDerivedItem(
          projectID: pid,
          sourceItemID: signal.sourceItemID,
          type: .signal,
          title: signal.title,
          bodyJSON: bodyStr,
          status: derivedStatus,
          confidence: signal.confidence,
          isCritical: signal.isCritical,
          createdAt: signal.createdAt,
          updatedAt: signal.createdAt,
          resolvedAt: signal.resolvedAt,
          resolutionReason: signal.resolutionReason
        )
        context.insert(item)
      } catch {
        AppLog.general.error("Migration: failed to migrate signal \(signal.title): \(error)")
      }
    }

    do {
      try context.save()
    } catch {
      AppLog.general.error("Migration: save failed: \(error)")
    }
    AppLog.general.info("Migration to ProjectDerivedItem complete")
    UserDefaults.standard.set(true, forKey: key)
  }

  // MARK: - Private

  private func assignColor() -> String {
    let active = (try? activeProjects()) ?? []
    var usage: [String: Int] = [:]
    for hex in ProjectPalette.allHexes { usage[hex] = 0 }
    for p in active {
      if let hex = p.colorHex { usage[hex, default: 0] += 1 }
    }
    return ProjectPalette.allHexes.min(by: { usage[$0]! < usage[$1]! })
      ?? ProjectPalette.allHexes[0]
  }

  func fetch(id: UUID) throws -> Project? {
    var descriptor = FetchDescriptor<Project>(predicate: #Predicate { $0.id == id })
    descriptor.fetchLimit = 1
    return try context.fetch(descriptor).first
  }

  func allProjects() throws -> [Project] {
    var descriptor = FetchDescriptor<Project>()
    descriptor.sortBy = [SortDescriptor(\.updatedAt, order: .reverse)]
    return try context.fetch(descriptor)
  }

  func activeProjects() throws -> [Project] {
    let active = ProjectStatus.active.rawValue
    var descriptor = FetchDescriptor<Project>(predicate: #Predicate { $0.statusRaw == active })
    descriptor.sortBy = [SortDescriptor(\.updatedAt, order: .reverse)]
    return try context.fetch(descriptor)
  }

  func items(in projectID: UUID) throws -> [KnowledgeItem] {
    var descriptor = FetchDescriptor<KnowledgeItem>(
      predicate: #Predicate { $0.projectID == projectID })
    descriptor.sortBy = [SortDescriptor(\.updatedAt, order: .reverse)]
    return try context.fetch(descriptor)
  }

  // MARK: - Derived items

  /// Returns all ProjectDerivedItems for this project.
  func derivedItems(in projectID: UUID) throws -> [ProjectDerivedItem] {
    let service = ProjectDerivedItemService(context: context)
    return try service.fetch(for: projectID)
  }

  /// Returns the synthesis for this project, if it exists.
  func synthesis(for projectID: UUID) throws -> ProjectDerivedItem? {
    let service = ProjectDerivedItemService(context: context)
    return try service.fetchSynthesis(for: projectID).first
  }

  /// Returns active tasks for this project.
  func activeTasks(in projectID: UUID) throws -> [ProjectDerivedItem] {
    let service = ProjectDerivedItemService(context: context)
    return try service.fetchActiveTasks(for: projectID)
  }

  /// Returns active signals for this project.
  func activeSignals(in projectID: UUID) throws -> [ProjectDerivedItem] {
    let service = ProjectDerivedItemService(context: context)
    return try service.fetchActiveSignals(for: projectID)
  }

  /// Unified count of all content (KnowledgeItems + ProjectDerivedItems) in this project.
  func totalContentCount(for projectID: UUID) throws -> Int {
    let items = try self.items(in: projectID)
    let derived = try derivedItems(in: projectID)
    return items.count + derived.count
  }

  /// Marks a KnowledgeItem as needing reprocessing with the given context.
  func markForReprocessing(itemID: UUID, projectID: UUID, context: String) throws {
    guard let item = try fetchItem(itemID) else { return }
    // Set reprocessing flag — the Item Agent picks this up
    item.needsProjectReprocessing = true
    item.projectReprocessContext = context
    item.updatedAt = Date()
    try self.context.save()
  }

  /// Assign an item to a project. Persists immediately.
  /// Pipeline must be started separately by the caller.
  func addItem(_ itemID: UUID, to projectID: UUID) throws {
    guard let item = try fetchItem(itemID) else {
      AppLog.provider.error("ProjectService.addItem: item \(itemID) not found in store")
      return
    }
    item.projectID = projectID
    item.updatedAt = Date()
    if item.inboxDate != nil {
      item.inboxDate = nil
    }
    try context.save()
    AppLog.provider.info("ProjectService.addItem: \(item.title) -> project \(projectID)")
  }

  func removeItem(_ itemID: UUID) throws {
    guard let item = try fetchItem(itemID) else { return }
    item.projectID = nil
    item.updatedAt = Date()
    try context.save()
  }

  func deleteProject(_ project: Project) throws {
    let items = try self.items(in: project.id)
    for item in items {
      item.projectID = nil
      item.updatedAt = Date()
    }
    let projectId: UUID? = project.id
    let tasks = try context.fetch(
      FetchDescriptor<TaskItem>(predicate: #Predicate { $0.projectID == projectId }))
    for task in tasks { context.delete(task) }
    let pid = project.id

    // Track deleted edge IDs to avoid double-deleting edges that connect
    // items to the project itself (both loops would match those edges).
    var deletedEdgeIDs = Set<UUID>()
    let edgesOut = try context.fetch(
      FetchDescriptor<GraphEdge>(predicate: #Predicate { $0.fromID == pid }))
    for edge in edgesOut {
      context.delete(edge)
      deletedEdgeIDs.insert(edge.id)
    }
    let edgesIn = try context.fetch(
      FetchDescriptor<GraphEdge>(predicate: #Predicate { $0.toID == pid }))
    for edge in edgesIn {
      context.delete(edge)
      deletedEdgeIDs.insert(edge.id)
    }

    // Clean up inter-item edges, skipping any already deleted in the project-level pass
    let itemIDs = items.map(\.id)
    for iid in itemIDs {
      let out = try context.fetch(
        FetchDescriptor<GraphEdge>(predicate: #Predicate { $0.fromID == iid }))
      for e in out where !deletedEdgeIDs.contains(e.id) { context.delete(e) }
      let incoming = try context.fetch(
        FetchDescriptor<GraphEdge>(predicate: #Predicate { $0.toID == iid }))
      for e in incoming where !deletedEdgeIDs.contains(e.id) { context.delete(e) }
    }
    context.delete(project)
    try context.save()
  }

  private func fetchItem(_ id: UUID) throws -> KnowledgeItem? {
    var descriptor = FetchDescriptor<KnowledgeItem>(predicate: #Predicate { $0.id == id })
    descriptor.fetchLimit = 1
    return try context.fetch(descriptor).first
  }
}
